feat: 컨펌뷰 추가완료
Nexters/Don-t-Forget---iOS pull request #22
Opened 2024-02-20 11:27 UTC by jife-archive

## #️⃣연관된 이슈

> #6 

## 📝작업 내용

> 컨펌뷰를 추가했습니다! 이제 순환그리드를 할려하는데.. 문센세이 정답을 아십니까?

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 이제 순환그리드를 할려하는데.. 문센세이 정답을 아십니까?
>이제 순환그리드를 할려하는데.. 문센세이 정답을 아십니까?
> 이제 순환그리드를 할려하는데.. 문센세이 정답을 아십니까?
>이제 순환그리드를 할려하는데.. 문센세이 정답을 아십니까?
>이제 순환그리드를 할려하는데.. 문센세이 정답을 아십니까?

2024-02-21 04:45 UTC, dayo2n commented
푸하핫^^;; [이슈의 댓글](https://github.com/Nexters/Don-t-Forget---iOS/issues/23#issuecomment-1955856965)을 참고하십시오... 저도 안해봤지말입니다?

2024-02-21 04:52 UTC, dayo2n requested changes

2024-02-21 04:52 UTC, dayo2n commented on DontForget/Sources/Presentations/Application/Common/ConfirmView.swift
> +            return "기념일 만들기를 취소할까용?"
라이팅을 맘대로 바꾸시면 어떡해요 슨생님

2024-02-21 04:52 UTC, dayo2n commented on DontForget/Sources/Presentations/Application/Creation/CreationView.swift
> +                    .zIndex(1)
오 이거 궁금한 점
안그래도 아카데미에서 마지막 프로젝트하는데 팀원 한 명이 zIndex를 너무 적극적으로 활용하는 바람에 모든 뷰에 z인덱스를 정해주면서 뷰 계층구조가 한 눈에 안보이고 한 번 수정하면 모든 뷰의 zIndex를 건드려야하는 경우가 발생했거든
이때 맥앱 + GeometryReader쓰면서 뷰 디버깅도 불가능했음
그래서 나는 보통 zIndex 사용은 지양하고 스택 순서대로 작성하긴 하는데 언제 어떻게 써야 좋을까..
지금처럼 모달 띄울 때정도면 쓰기 딱 좋으려나 ??

2024-02-21 04:52 UTC, dayo2n commented on DontForget/Sources/Presentations/Application/Creation/CreationView.swift
> +                            print("asdsad")
ꖶዞዞ 이렇게 asdsad 프린트를 좋아하ㅡㄴ거얔ㅋㅋㅋㅋㅋㅋㅋ

2024-02-21 04:52 UTC, dayo2n commented on DontForget/Sources/Presentations/Application/Edit/EditView.swift
> +        CreationView(viewModel: CreationViewModel(creationUseCase: CreationUseCase(creationRepository: CreationRepository(service: AnniversaryService()))))
```suggestion
        CreationView(
          viewModel: CreationViewModel(
            creationUseCase: CreationUseCase(
              creationRepository: CreationRepository(
                service: AnniversaryService()
              )
            )
          )
        )
```

2024-02-21 04:52 UTC, dayo2n commented on DontForget/Sources/Presentations/Application/Edit/EditViewModel.swift
> +
아직 비워둔거죠 ???

2024-02-22 00:54 UTC, jife-archive commented on DontForget/Sources/Presentations/Application/Common/ConfirmView.swift
> +            return "기념일 만들기를 취소할까용?"
죄송..ㅎ.ㅎ

2024-02-22 00:55 UTC, jife-archive commented on DontForget/Sources/Presentations/Application/Creation/CreationView.swift
> +                    .zIndex(1)
그게 딱 맞을꺼 같아 너의 의견에 상당히 동의해, 난 더군다다 ZStack을 사용하는걸 별로 안조아하는데 플로팅버튼땜시 사용한거라서 Zindex를 사용해서 계속 인덱스 주고 차곡차곡하면 가독성은 물론 유지보수도 별루 일 것 같아잉

2024-02-22 00:56 UTC, jife-archive commented on DontForget/Sources/Presentations/Application/Creation/CreationView.swift
> +                            print("asdsad")
😅 안지웠네 저걸 죄송머쓱

2024-02-22 00:56 UTC, jife-archive commented on DontForget/Sources/Presentations/Application/Edit/EditView.swift
> +        CreationView(viewModel: CreationViewModel(creationUseCase: CreationUseCase(creationRepository: CreationRepository(service: AnniversaryService()))))
아 이거진짜 미안 ㅎ,ㅎ

2024-02-22 00:56 UTC, jife-archive commented on DontForget/Sources/Presentations/Application/Edit/EditViewModel.swift
> +
어? 이게 같이 딸려들어갔네 이 파일 자체를 다 날리면돼 내가 날리고 다시할게융

2024-02-22 02:58 UTC, dayo2n approved these changes
오께이 ~~~ 미리 어프루브남길테니 수정하고 오빠가 머지 고고~!~

2024-02-23 13:39 UTC, merged